### ISSUE TITLE
Milestone 01 feedback

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/picfixR#6]
Hello,
You did a great job on your milestone 01 submission. I just have some comments below,
- Good job using `roxygen2` for generating function documentation.
- You should create the directories for saving the test images for example  `"test_img/contrast"`.
- You should add more informative description to your functions.

Thanks!

**Comment by GeorgeJJW** [comment]
Hello @hsmohammed,

We reorganized our repo structure so that test images for each function are now living in the appropriate folder.

We also added more informative description to our functions in the README.md, showcasing their usages and effects. We also expanded the documentation for each function.

Thank you for your timely feedback!
